using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using BudgetSys.Models;
using IniParser;
using IniParser.Model;
using Microsoft.Win32;
using BudgetSys.Repositories;

namespace BudgetSys
{
    /// <summary>
    /// MainWindow.xaml 的交互逻辑
    /// </summary>
    public partial class MainWindow : Window
    {
        IniData data;

        MetalBatch currentBatch;


        private RawMaterial editMetal;

        private IMatetrialRepository matetrialRepository;

        public MainWindow()
        {
            this.Loaded += MainWindow_Loaded;
            FileIniDataParser parser = new FileIniDataParser();
            data = parser.ReadFile("Config.ini", Encoding.UTF8);
            InitializeComponent();
        }

        private void MainWindow_Loaded(object sender, RoutedEventArgs e)
        {
            this.materialType.ItemsSource = Enum.GetValues(typeof(BatchType)).Cast<BatchType>();
            this.materialType.SelectedIndex = 0;    
        }

        private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
          matetrialRepository.AutoGenColumn(e);
        }

        private void DataGrid_CellEditEnding(object sender, DataGridCellEditEndingEventArgs e)
        {
            editMetal = e.Row.Item as RawMaterial;
            //editMetal.EndEdit();
        }

        private void DataGrid_AddingNewItem(object sender, AddingNewItemEventArgs e)
        {
            var newId = (sender as DataGrid).Items.Count ;
            var batchNo = currentBatch?.batchNo;
            e.NewItem = matetrialRepository.AddNewItem(newId, batchNo);
            //metal.id = ((sender as DataGrid).ItemsSource as ObservableCollection<Metal>).Count + 1;
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            matetrialRepository.Save(this.DataContext, currentBatch);

            //lvBatch.ItemsSource = matetrialRepository.GetBatches();
        }

        /// <summary>
        /// 加载批次
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void ListView_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            var batch = (sender as ListView).SelectedItem as MetalBatch;

            this.DataContext = matetrialRepository.CreateViewModel(batch);

            currentBatch = batch;
        }

        /// <summary>
        /// 重计
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void DataGrid_CurrentCellChanged(object sender, EventArgs e)
        {
            var metal = editMetal;
            matetrialRepository.Calculate(metal);
        }



        private void DgDetail_BeginningEdit(object sender, DataGridBeginningEditEventArgs e)
        {
            editMetal?.EndEdit();

            //this.dgDetail.CommitEdit(DataGridEditingUnit.Row, true);
        }



        /// <summary>
        /// 新建批次
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnNew_Click(object sender, RoutedEventArgs e)
        {
            this.DataContext = matetrialRepository.CreateViewModel();
            currentBatch = null;
        }

        /// <summary>
        /// 删除记录
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnDelete_Click(object sender, RoutedEventArgs e)
        {
            matetrialRepository.Delete(this.dgDetail.DataContext, this.dgDetail.SelectedItem);
        }

        private void BtnBatchDelete_Click(object sender, RoutedEventArgs e)
        {

        }

        private void ComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if ((BatchType)((e.Source as ComboBox).SelectedItem) == BatchType.Metal)
                matetrialRepository = new MetalRepository();
            else
                matetrialRepository = new PlasticRepository();

            this.DataContext = matetrialRepository.CreateViewModel();
            editMetal = null;
            currentBatch = null;
        }

        private void DgDetail_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (DataGridColumn col in dgDetail.Columns)
            {
                try
                {
                    matetrialRepository.RenameColumn(col);
                }
                catch (Exception)
                {
                    continue;
                }
          
            }
        }

        private void TextBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            var search = (e.Source as TextBox).Text;
            foreach (MetalBatch item in lvBatch.Items)
            {
                if (item.batchNo.Contains(search))
                {
                    lvBatch.SelectedItem = item;
                    break;
                }
            }
        }
    }
}
