using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using BudgetSys.Models;

namespace BudgetSys
{
    /// <summary>
    /// SaveWindow.xaml 的交互逻辑
    /// </summary>
    public partial class SaveWindow: Window 
    {
        public event Action<object> OnSave;

        public SaveWindow(object viewModel)
        {
            this.DataContext = viewModel;
            InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            if (OnSave != null)
                OnSave(this.DataContext);
            this.Close();
        }

        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            this.Close();
        }

        private void DataGrid_AddingNewItem(object sender, AddingNewItemEventArgs e)
        {
            
        }

        private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            //if (e.PropertyName.ToUpper() == "ID")
            //    e.Cancel = true;
            if (e.PropertyName == "id")
            {
                e.Column.IsReadOnly = true;
            }
        }

        private void DataGrid_InitializingNewItem(object sender, InitializingNewItemEventArgs e)
        {
            var dg = sender as DataGrid;
            PropertyInfo prop = e.NewItem.GetType().GetProperty("id", BindingFlags.Public | BindingFlags.Instance);
            if (null != prop && prop.CanWrite)
            {
                prop.SetValue(e.NewItem, dg.Items.Count-2, null);
            }
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var dgDetail = sender as DataGrid;
            foreach (DataGridColumn col in dgDetail.Columns)
            {
                if (col.Header.ToString() == "id")
                {
                    col.DisplayIndex = 0;
                }
            }
        }
    }
}
